add_test([=[ExchangeTest.ConstructorAndGetName]=]  /home/runner/work/crex/crex/_codeql_build_dir/tests/crex_test [==[--gtest_filter=ExchangeTest.ConstructorAndGetName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExchangeTest.ConstructorAndGetName]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/crex/crex/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExchangeTest.SetAndGetBalance]=]  /home/runner/work/crex/crex/_codeql_build_dir/tests/crex_test [==[--gtest_filter=ExchangeTest.SetAndGetBalance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExchangeTest.SetAndGetBalance]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/crex/crex/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExchangeTest.GetBalanceNonExistentCurrency]=]  /home/runner/work/crex/crex/_codeql_build_dir/tests/crex_test [==[--gtest_filter=ExchangeTest.GetBalanceNonExistentCurrency]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExchangeTest.GetBalanceNonExistentCurrency]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/crex/crex/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExchangeTest.AddBalance]=]  /home/runner/work/crex/crex/_codeql_build_dir/tests/crex_test [==[--gtest_filter=ExchangeTest.AddBalance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExchangeTest.AddBalance]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/crex/crex/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExchangeTest.AddBalanceNewCurrency]=]  /home/runner/work/crex/crex/_codeql_build_dir/tests/crex_test [==[--gtest_filter=ExchangeTest.AddBalanceNewCurrency]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExchangeTest.AddBalanceNewCurrency]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/crex/crex/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExchangeTest.HasCurrency]=]  /home/runner/work/crex/crex/_codeql_build_dir/tests/crex_test [==[--gtest_filter=ExchangeTest.HasCurrency]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExchangeTest.HasCurrency]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/crex/crex/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExchangeTest.MultipleCurrencies]=]  /home/runner/work/crex/crex/_codeql_build_dir/tests/crex_test [==[--gtest_filter=ExchangeTest.MultipleCurrencies]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExchangeTest.MultipleCurrencies]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/crex/crex/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  crex_test_TESTS ExchangeTest.ConstructorAndGetName ExchangeTest.SetAndGetBalance ExchangeTest.GetBalanceNonExistentCurrency ExchangeTest.AddBalance ExchangeTest.AddBalanceNewCurrency ExchangeTest.HasCurrency ExchangeTest.MultipleCurrencies)
